name: new_apta_grading
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  another_flushbar: ^1.12.32
  connectivity_plus: ^7.0.0
  dio: ^5.9.0
  dotted_border: ^3.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^6.0.0
  flutter_localization: ^0.3.3
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.3.3
  image_picker: ^1.2.1
  intl: ^0.20.2
  lucide_icons: ^0.257.0
  open_file: ^3.5.10
  package_info_plus: ^9.0.0
  path: ^1.9.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  pub_semver: ^2.2.0
  shared_preferences: ^2.5.4
  talker_dio_logger: ^5.1.9

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - .dev.env
    - .arp.env
    - .emj.env
    - .kpj.env
    - .pks.env
